#ifndef OLRN_PELENTAR_IMPL_H
#define OLRN_PELENTAR_IMPL_H

/* C++ implementation injected when @std.crypt is imported.
   libsodium backend; all helpers use the _olrn_crypt_ prefix.
   Result values are stored in a thread-local string (_pe_tl) and
   retrieved with _olrn_crypt_get_result() after a bool-returning call. */
static const char *CRYPT_IMPL =
    "/* ── crypt cryptography library (libsodium backend) ─────── */\n"
    "#include <sodium.h>\n"
    "#include <fstream>\n"
    "#include <sstream>\n"
    "#include <vector>\n"
    "#include <cstring>\n"
    "\n"
    "struct CryptKeyPair     { std::string pub_key;    std::string sec_key;  };\n"
    "struct CryptSignKeyPair { std::string verify_key; std::string sign_key; };\n"
    "\n"
    "static thread_local std::string _pe_tl;\n"
    "\n"
    "static bool _pe_init() {\n"
    "    static int _s = sodium_init();\n"
    "    return _s >= 0;\n"
    "}\n"
    "\n"
    "static std::string _pe_hex(const uint8_t *d, size_t n) {\n"
    "    std::string s(n * 2 + 1, 0);\n"
    "    sodium_bin2hex(&s[0], s.size(), d, n);\n"
    "    s.resize(n * 2);\n"
    "    return s;\n"
    "}\n"
    "\n"
    "static bool _pe_unhex(const std::string &h, std::vector<uint8_t> &out) {\n"
    "    out.resize(h.size() / 2 + 1);\n"
    "    size_t bl = 0;\n"
    "    if (sodium_hex2bin(out.data(), out.size(), h.c_str(), h.size(),\n"
    "                       nullptr, &bl, nullptr) != 0) return false;\n"
    "    out.resize(bl);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static std::string _pe_b64(const uint8_t *d, size_t n) {\n"
    "    size_t len = sodium_base64_encoded_len(n, sodium_base64_VARIANT_ORIGINAL);\n"
    "    std::string s(len, 0);\n"
    "    sodium_bin2base64(&s[0], len, d, n, sodium_base64_VARIANT_ORIGINAL);\n"
    "    s.resize(strlen(s.c_str()));\n"
    "    return s;\n"
    "}\n"
    "\n"
    "static bool _pe_unb64(const std::string &b, std::vector<uint8_t> &out) {\n"
    "    out.resize(b.size());\n"
    "    size_t bl = 0;\n"
    "    if (sodium_base642bin(out.data(), out.size(), b.c_str(), b.size(),\n"
    "                          nullptr, &bl, nullptr,\n"
    "                          sodium_base64_VARIANT_ORIGINAL) != 0) return false;\n"
    "    out.resize(bl);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static unsigned long long _pe_ops(int32_t s) {\n"
    "    return s == 0 ? crypto_pwhash_OPSLIMIT_INTERACTIVE\n"
    "         : s == 2 ? crypto_pwhash_OPSLIMIT_SENSITIVE\n"
    "                  : crypto_pwhash_OPSLIMIT_MODERATE;\n"
    "}\n"
    "static size_t _pe_mem(int32_t s) {\n"
    "    return s == 0 ? (size_t)crypto_pwhash_MEMLIMIT_INTERACTIVE\n"
    "         : s == 2 ? (size_t)crypto_pwhash_MEMLIMIT_SENSITIVE\n"
    "                  : (size_t)crypto_pwhash_MEMLIMIT_MODERATE;\n"
    "}\n"
    "\n"
    "static std::string _olrn_crypt_get_result() { return _pe_tl; }\n"
    "\n"
    "/* ── password hashing (Argon2id) ──────────────────────────── */\n"
    "static bool _olrn_crypt_hashpk(int32_t s, const std::string &plain) {\n"
    "    if (!_pe_init()) return false;\n"
    "    char h[crypto_pwhash_STRBYTES];\n"
    "    if (crypto_pwhash_str(h, plain.c_str(), plain.size(),\n"
    "                          _pe_ops(s), _pe_mem(s)) != 0) return false;\n"
    "    _pe_tl = h;\n"
    "    return true;\n"
    "}\n"
    "\n"
    "/* Returns: -1 = init failed, 0 = no match, 1 = match.\n"
    "   stren is accepted as a hint but ignored — cost params are\n"
    "   embedded in the hash string by hashpk. */\n"
    "static int32_t _olrn_crypt_auth_hashpk(const std::string &plain,\n"
    "                                     const std::string &hashed) {\n"
    "    if (!_pe_init()) return -1;\n"
    "    return crypto_pwhash_str_verify(hashed.c_str(),\n"
    "        plain.c_str(), plain.size()) == 0 ? 1 : 0;\n"
    "}\n"
    "\n"
    "/* ── hashing ───────────────────────────────────────────────── */\n"
    "static std::string _olrn_crypt_hash(int32_t algo, const std::string &data) {\n"
    "    if (!_pe_init()) return \"\";\n"
    "    if (algo == 0) {\n"
    "        uint8_t o[crypto_hash_sha256_BYTES];\n"
    "        crypto_hash_sha256(o, (const uint8_t *)data.data(), data.size());\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    } else if (algo == 1) {\n"
    "        uint8_t o[crypto_hash_sha512_BYTES];\n"
    "        crypto_hash_sha512(o, (const uint8_t *)data.data(), data.size());\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    } else {\n"
    "        uint8_t o[32];\n"
    "        crypto_generichash(o, sizeof(o),\n"
    "            (const uint8_t *)data.data(), data.size(), nullptr, 0);\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    }\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_hash_file(int32_t algo, const std::string &path) {\n"
    "    std::ifstream f(path, std::ios::binary);\n"
    "    if (!f) return false;\n"
    "    std::ostringstream ss;\n"
    "    ss << f.rdbuf();\n"
    "    _pe_tl = _olrn_crypt_hash(algo, ss.str());\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static std::string _olrn_crypt_hmac(int32_t algo, const std::string &key,\n"
    "                                   const std::string &data) {\n"
    "    if (!_pe_init()) return \"\";\n"
    "    if (algo == 1) {\n"
    "        uint8_t o[crypto_auth_hmacsha512_BYTES];\n"
    "        crypto_auth_hmacsha512_state st;\n"
    "        crypto_auth_hmacsha512_init(&st,\n"
    "            (const uint8_t *)key.data(), key.size());\n"
    "        crypto_auth_hmacsha512_update(&st,\n"
    "            (const uint8_t *)data.data(), data.size());\n"
    "        crypto_auth_hmacsha512_final(&st, o);\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    } else if (algo == 2) {\n"
    "        uint8_t o[32];\n"
    "        size_t kl = key.size();\n"
    "        if (kl < (size_t)crypto_generichash_KEYBYTES_MIN)\n"
    "            kl = crypto_generichash_KEYBYTES_MIN;\n"
    "        if (kl > (size_t)crypto_generichash_KEYBYTES_MAX)\n"
    "            kl = crypto_generichash_KEYBYTES_MAX;\n"
    "        std::vector<uint8_t> kb(kl, 0);\n"
    "        size_t cp = key.size() < kl ? key.size() : kl;\n"
    "        memcpy(kb.data(), key.data(), cp);\n"
    "        crypto_generichash(o, sizeof(o),\n"
    "            (const uint8_t *)data.data(), data.size(),\n"
    "            kb.data(), kl);\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    } else {\n"
    "        uint8_t o[crypto_auth_hmacsha256_BYTES];\n"
    "        crypto_auth_hmacsha256_state st;\n"
    "        crypto_auth_hmacsha256_init(&st,\n"
    "            (const uint8_t *)key.data(), key.size());\n"
    "        crypto_auth_hmacsha256_update(&st,\n"
    "            (const uint8_t *)data.data(), data.size());\n"
    "        crypto_auth_hmacsha256_final(&st, o);\n"
    "        return _pe_hex(o, sizeof(o));\n"
    "    }\n"
    "}\n"
    "\n"
    "/* ── symmetric AEAD (XChaCha20-Poly1305) ──────────────────── */\n"
    "static std::string _olrn_crypt_keygen() {\n"
    "    if (!_pe_init()) return \"\";\n"
    "    uint8_t k[crypto_aead_xchacha20poly1305_ietf_KEYBYTES];\n"
    "    crypto_aead_xchacha20poly1305_ietf_keygen(k);\n"
    "    return _pe_hex(k, sizeof(k));\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_encrypt(const std::string &kh,\n"
    "                              const std::string &plain) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::vector<uint8_t> k;\n"
    "    if (!_pe_unhex(kh, k) ||\n"
    "        k.size() != crypto_aead_xchacha20poly1305_ietf_KEYBYTES) return false;\n"
    "    uint8_t nonce[crypto_aead_xchacha20poly1305_ietf_NPUBBYTES];\n"
    "    randombytes_buf(nonce, sizeof(nonce));\n"
    "    std::vector<uint8_t> ct(plain.size() +\n"
    "                             crypto_aead_xchacha20poly1305_ietf_ABYTES);\n"
    "    unsigned long long cl;\n"
    "    crypto_aead_xchacha20poly1305_ietf_encrypt(\n"
    "        ct.data(), &cl,\n"
    "        (const uint8_t *)plain.data(), plain.size(),\n"
    "        nullptr, 0, nullptr, nonce, k.data());\n"
    "    std::vector<uint8_t> blob(sizeof(nonce) + (size_t)cl);\n"
    "    memcpy(blob.data(), nonce, sizeof(nonce));\n"
    "    memcpy(blob.data() + sizeof(nonce), ct.data(), cl);\n"
    "    _pe_tl = _pe_b64(blob.data(), blob.size());\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_decrypt(const std::string &kh,\n"
    "                              const std::string &b64) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::vector<uint8_t> k;\n"
    "    if (!_pe_unhex(kh, k) ||\n"
    "        k.size() != crypto_aead_xchacha20poly1305_ietf_KEYBYTES) return false;\n"
    "    std::vector<uint8_t> blob;\n"
    "    if (!_pe_unb64(b64, blob)) return false;\n"
    "    const size_t nlen = crypto_aead_xchacha20poly1305_ietf_NPUBBYTES;\n"
    "    const size_t alen = crypto_aead_xchacha20poly1305_ietf_ABYTES;\n"
    "    if (blob.size() < nlen + alen) return false;\n"
    "    std::vector<uint8_t> plain(blob.size() - nlen - alen + 1);\n"
    "    unsigned long long pl;\n"
    "    if (crypto_aead_xchacha20poly1305_ietf_decrypt(\n"
    "            plain.data(), &pl, nullptr,\n"
    "            blob.data() + nlen, blob.size() - nlen,\n"
    "            nullptr, 0, blob.data(), k.data()) != 0) return false;\n"
    "    _pe_tl = std::string((char *)plain.data(), pl);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "/* ── asymmetric box (X25519 + XSalsa20-Poly1305) ──────────── */\n"
    "static CryptKeyPair _olrn_crypt_box_keygen() {\n"
    "    if (!_pe_init()) return {\"\", \"\"};\n"
    "    uint8_t pk[crypto_box_PUBLICKEYBYTES];\n"
    "    uint8_t sk[crypto_box_SECRETKEYBYTES];\n"
    "    crypto_box_keypair(pk, sk);\n"
    "    return {_pe_hex(pk, sizeof(pk)), _pe_hex(sk, sizeof(sk))};\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_box_encrypt(const std::string &sk_h,\n"
    "                                   const std::string &pk_h,\n"
    "                                   const std::string &plain) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::vector<uint8_t> sk, pk;\n"
    "    if (!_pe_unhex(sk_h, sk) ||\n"
    "        sk.size() != crypto_box_SECRETKEYBYTES) return false;\n"
    "    if (!_pe_unhex(pk_h, pk) ||\n"
    "        pk.size() != crypto_box_PUBLICKEYBYTES) return false;\n"
    "    uint8_t nonce[crypto_box_NONCEBYTES];\n"
    "    randombytes_buf(nonce, sizeof(nonce));\n"
    "    std::vector<uint8_t> ct(plain.size() + crypto_box_MACBYTES);\n"
    "    if (crypto_box_easy(ct.data(), (const uint8_t *)plain.data(),\n"
    "                        plain.size(), nonce,\n"
    "                        pk.data(), sk.data()) != 0) return false;\n"
    "    std::vector<uint8_t> blob(sizeof(nonce) + ct.size());\n"
    "    memcpy(blob.data(), nonce, sizeof(nonce));\n"
    "    memcpy(blob.data() + sizeof(nonce), ct.data(), ct.size());\n"
    "    _pe_tl = _pe_b64(blob.data(), blob.size());\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_box_decrypt(const std::string &sk_h,\n"
    "                                   const std::string &pk_h,\n"
    "                                   const std::string &b64) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::vector<uint8_t> sk, pk;\n"
    "    if (!_pe_unhex(sk_h, sk) ||\n"
    "        sk.size() != crypto_box_SECRETKEYBYTES) return false;\n"
    "    if (!_pe_unhex(pk_h, pk) ||\n"
    "        pk.size() != crypto_box_PUBLICKEYBYTES) return false;\n"
    "    std::vector<uint8_t> blob;\n"
    "    if (!_pe_unb64(b64, blob)) return false;\n"
    "    const size_t nlen = crypto_box_NONCEBYTES;\n"
    "    if (blob.size() < nlen + crypto_box_MACBYTES) return false;\n"
    "    size_t ptlen = blob.size() - nlen - crypto_box_MACBYTES;\n"
    "    std::vector<uint8_t> plain(ptlen + 1);\n"
    "    if (crypto_box_open_easy(plain.data(),\n"
    "                             blob.data() + nlen, blob.size() - nlen,\n"
    "                             blob.data(),\n"
    "                             pk.data(), sk.data()) != 0) return false;\n"
    "    _pe_tl = std::string((char *)plain.data(), ptlen);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "/* ── signatures (Ed25519) ──────────────────────────────────── */\n"
    "static CryptSignKeyPair _olrn_crypt_sign_keygen() {\n"
    "    if (!_pe_init()) return {\"\", \"\"};\n"
    "    uint8_t pk[crypto_sign_PUBLICKEYBYTES];\n"
    "    uint8_t sk[crypto_sign_SECRETKEYBYTES];\n"
    "    crypto_sign_keypair(pk, sk);\n"
    "    return {_pe_hex(pk, sizeof(pk)), _pe_hex(sk, sizeof(sk))};\n"
    "}\n"
    "\n"
    "static std::string _olrn_crypt_sign(const std::string &sk_h,\n"
    "                                   const std::string &msg) {\n"
    "    if (!_pe_init()) return \"\";\n"
    "    std::vector<uint8_t> sk;\n"
    "    if (!_pe_unhex(sk_h, sk) ||\n"
    "        sk.size() != crypto_sign_SECRETKEYBYTES) return \"\";\n"
    "    uint8_t sig[crypto_sign_BYTES];\n"
    "    unsigned long long sl;\n"
    "    crypto_sign_detached(sig, &sl, (const uint8_t *)msg.data(),\n"
    "                         msg.size(), sk.data());\n"
    "    return _pe_hex(sig, sl);\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_verify(const std::string &vk_h, const std::string &msg,\n"
    "                              const std::string &sig_h) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::vector<uint8_t> vk, sig;\n"
    "    if (!_pe_unhex(vk_h, vk) ||\n"
    "        vk.size() != crypto_sign_PUBLICKEYBYTES) return false;\n"
    "    if (!_pe_unhex(sig_h, sig) ||\n"
    "        sig.size() != crypto_sign_BYTES) return false;\n"
    "    return crypto_sign_verify_detached(sig.data(),\n"
    "        (const uint8_t *)msg.data(), msg.size(), vk.data()) == 0;\n"
    "}\n"
    "\n"
    "/* ── KDF (Argon2id) ────────────────────────────────────────── */\n"
    "static bool _olrn_crypt_kdf(int32_t s, const std::string &pass,\n"
    "                          const std::string &salt_h, int32_t klen) {\n"
    "    if (!_pe_init() || klen <= 0) return false;\n"
    "    std::vector<uint8_t> salt;\n"
    "    if (!_pe_unhex(salt_h, salt) ||\n"
    "        salt.size() < crypto_pwhash_SALTBYTES) return false;\n"
    "    std::vector<uint8_t> key(klen);\n"
    "    if (crypto_pwhash(key.data(), klen,\n"
    "                      pass.c_str(), pass.size(), salt.data(),\n"
    "                      _pe_ops(s), _pe_mem(s),\n"
    "                      crypto_pwhash_ALG_ARGON2ID13) != 0) return false;\n"
    "    _pe_tl = _pe_hex(key.data(), klen);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "/* ── random ────────────────────────────────────────────────── */\n"
    "static std::string _olrn_crypt_rand_bytes(int32_t n) {\n"
    "    if (!_pe_init() || n <= 0) return \"\";\n"
    "    std::string s(n, 0);\n"
    "    randombytes_buf(&s[0], n);\n"
    "    return s;\n"
    "}\n"
    "\n"
    "static std::string _olrn_crypt_rand_hex(int32_t n) {\n"
    "    if (!_pe_init() || n <= 0) return \"\";\n"
    "    std::vector<uint8_t> b(n);\n"
    "    randombytes_buf(b.data(), n);\n"
    "    return _pe_hex(b.data(), n);\n"
    "}\n"
    "\n"
    "/* ── encoding utilities ────────────────────────────────────── */\n"
    "static std::string _olrn_crypt_base64_encode(const std::string &data) {\n"
    "    return _pe_b64((const uint8_t *)data.data(), data.size());\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_base64_decode(const std::string &b64) {\n"
    "    std::vector<uint8_t> out;\n"
    "    if (!_pe_unb64(b64, out)) return false;\n"
    "    _pe_tl = std::string((char *)out.data(), out.size());\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static std::string _olrn_crypt_hex_encode(const std::string &data) {\n"
    "    return _pe_hex((const uint8_t *)data.data(), data.size());\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_hex_decode(const std::string &hex) {\n"
    "    std::vector<uint8_t> out;\n"
    "    if (!_pe_unhex(hex, out)) return false;\n"
    "    _pe_tl = std::string((char *)out.data(), out.size());\n"
    "    return true;\n"
    "}\n"
    "\n"
    "/* ── file encryption ───────────────────────────────────────── */\n"
    "/* File format:\n"
    "   PLNT(4) | ver(1)=0x01 | stren(1) | cipher(1) | salt(32) | nonce | ct+tag\n"
    "   cipher: 1=AES-256-GCM (nonce=12), 2=XChaCha20-Poly1305 (nonce=24)\n"
    "   FAST/DEFAULT use AES-256-GCM when crypto_aead_aes256gcm_is_available(),\n"
    "   otherwise fall back to XChaCha20-Poly1305. STRONG always uses XChaCha20. */\n"
    "static bool _olrn_crypt_enc_file(int32_t s, const std::string &path,\n"
    "                               const std::string &pk) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::ifstream fin(path, std::ios::binary);\n"
    "    if (!fin) return false;\n"
    "    std::string plain((std::istreambuf_iterator<char>(fin)),\n"
    "                       std::istreambuf_iterator<char>());\n"
    "    fin.close();\n"
    "    /* 32-byte salt (Argon2id uses first crypto_pwhash_SALTBYTES = 16) */\n"
    "    uint8_t salt[32];\n"
    "    randombytes_buf(salt, sizeof(salt));\n"
    "    bool use_aes = (s != 2) && crypto_aead_aes256gcm_is_available();\n"
    "    uint8_t cipher_id = use_aes ? 1 : 2;\n"
    "    size_t klen   = use_aes ? crypto_aead_aes256gcm_KEYBYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_KEYBYTES;\n"
    "    size_t nlen   = use_aes ? crypto_aead_aes256gcm_NPUBBYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_NPUBBYTES;\n"
    "    size_t abytes = use_aes ? crypto_aead_aes256gcm_ABYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_ABYTES;\n"
    "    std::vector<uint8_t> key(klen);\n"
    "    if (crypto_pwhash(key.data(), klen, pk.c_str(), pk.size(), salt,\n"
    "                      _pe_ops(s), _pe_mem(s),\n"
    "                      crypto_pwhash_ALG_ARGON2ID13) != 0) return false;\n"
    "    std::vector<uint8_t> nonce(nlen);\n"
    "    randombytes_buf(nonce.data(), nlen);\n"
    "    std::vector<uint8_t> ct(plain.size() + abytes);\n"
    "    unsigned long long cl;\n"
    "    if (use_aes) {\n"
    "        crypto_aead_aes256gcm_encrypt(\n"
    "            ct.data(), &cl,\n"
    "            (const uint8_t *)plain.data(), plain.size(),\n"
    "            nullptr, 0, nullptr, nonce.data(), key.data());\n"
    "    } else {\n"
    "        crypto_aead_xchacha20poly1305_ietf_encrypt(\n"
    "            ct.data(), &cl,\n"
    "            (const uint8_t *)plain.data(), plain.size(),\n"
    "            nullptr, 0, nullptr, nonce.data(), key.data());\n"
    "    }\n"
    "    std::ofstream fout(path, std::ios::binary | std::ios::trunc);\n"
    "    if (!fout) return false;\n"
    "    fout.write(\"PLNT\", 4);\n"
    "    uint8_t hdr[3] = {0x01, (uint8_t)s, cipher_id};\n"
    "    fout.write((char *)hdr, 3);\n"
    "    fout.write((char *)salt, 32);\n"
    "    fout.write((char *)nonce.data(), (std::streamsize)nlen);\n"
    "    fout.write((char *)ct.data(), (std::streamsize)cl);\n"
    "    return true;\n"
    "}\n"
    "\n"
    "static bool _olrn_crypt_dec_file(int32_t /*s*/, const std::string &path,\n"
    "                               const std::string &pk) {\n"
    "    if (!_pe_init()) return false;\n"
    "    std::ifstream fin(path, std::ios::binary);\n"
    "    if (!fin) return false;\n"
    "    std::string raw((std::istreambuf_iterator<char>(fin)),\n"
    "                     std::istreambuf_iterator<char>());\n"
    "    fin.close();\n"
    "    /* minimum header: magic(4)+ver/stren/cipher(3)+salt(32)+nonce_min(12) */\n"
    "    if (raw.size() < 4 + 3 + 32 + 12) return false;\n"
    "    if (memcmp(raw.data(), \"PLNT\", 4) != 0) return false;\n"
    "    int32_t fs        = (uint8_t)raw[5];\n"
    "    uint8_t cipher_id = (uint8_t)raw[6];\n"
    "    const uint8_t *salt = (const uint8_t *)raw.data() + 7;\n"
    "    bool use_aes = (cipher_id == 1);\n"
    "    size_t klen   = use_aes ? crypto_aead_aes256gcm_KEYBYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_KEYBYTES;\n"
    "    size_t nlen   = use_aes ? crypto_aead_aes256gcm_NPUBBYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_NPUBBYTES;\n"
    "    size_t abytes = use_aes ? crypto_aead_aes256gcm_ABYTES\n"
    "                            : crypto_aead_xchacha20poly1305_ietf_ABYTES;\n"
    "    const size_t HDR = 4 + 3 + 32 + nlen;\n"
    "    if (raw.size() < HDR + abytes) return false;\n"
    "    const uint8_t *nonce = salt + 32;\n"
    "    const uint8_t *ct    = nonce + nlen;\n"
    "    size_t ctlen = raw.size() - HDR;\n"
    "    std::vector<uint8_t> key(klen);\n"
    "    if (crypto_pwhash(key.data(), klen, pk.c_str(), pk.size(), salt,\n"
    "                      _pe_ops(fs), _pe_mem(fs),\n"
    "                      crypto_pwhash_ALG_ARGON2ID13) != 0) return false;\n"
    "    std::vector<uint8_t> plain(ctlen - abytes + 1);\n"
    "    unsigned long long pl;\n"
    "    int rc;\n"
    "    if (use_aes) {\n"
    "        rc = crypto_aead_aes256gcm_decrypt(\n"
    "            plain.data(), &pl, nullptr,\n"
    "            ct, ctlen, nullptr, 0, nonce, key.data());\n"
    "    } else {\n"
    "        rc = crypto_aead_xchacha20poly1305_ietf_decrypt(\n"
    "            plain.data(), &pl, nullptr,\n"
    "            ct, ctlen, nullptr, 0, nonce, key.data());\n"
    "    }\n"
    "    if (rc != 0) return false;\n"
    "    std::ofstream fout(path, std::ios::binary | std::ios::trunc);\n"
    "    if (!fout) return false;\n"
    "    fout.write((char *)plain.data(), (std::streamsize)pl);\n"
    "    return true;\n"
    "}\n"
    "/* ── crypt end ──────────────────────────────────────────── */\n";

#endif /* OLRN_PELENTAR_IMPL_H */
