#ifndef OLRN_MALKUR_IMPL_H
#define OLRN_MALKUR_IMPL_H

/* C++ implementation injected when @std.malkur is imported.
   SDL2 backend; window/renderer/input live in one global state blob.
   All helpers use the _olrn_mk_ prefix. */
static const char *MALKUR_IMPL =
    "/* ── malkur gamedev library (SDL2 backend) ─────────────────────── */\n"
    "#include <SDL2/SDL.h>\n"
    "#include <cstring>\n"
    "\n"
    "struct Color    { uint8_t r, g, b, a; };\n"
    "struct Vec2     { float x, y; };\n"
    "struct Rect     { float x, y, w, h; };\n"
    "struct Camera2D { Vec2 target; Vec2 offset; float rotation; float zoom; };\n"
    "\n"
    "/* ── embedded 8x8 bitmap font (ASCII 32-126) ────────────────────── */\n"
    "static const uint8_t _mk_font8[95][8] = {\n"
    "    {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}, /* space */\n"
    "    {0x18,0x18,0x18,0x18,0x18,0x00,0x18,0x00}, /* ! */\n"
    "    {0x66,0x66,0x24,0x00,0x00,0x00,0x00,0x00}, /* \" */\n"
    "    {0x6C,0x6C,0xFE,0x6C,0xFE,0x6C,0x6C,0x00}, /* # */\n"
    "    {0x18,0x7E,0xC0,0x7C,0x06,0xFC,0x18,0x00}, /* $ */\n"
    "    {0x00,0xC6,0xCC,0x18,0x30,0x66,0xC6,0x00}, /* % */\n"
    "    {0x38,0x6C,0x38,0x76,0xDC,0xCC,0x76,0x00}, /* & */\n"
    "    {0x06,0x0C,0x18,0x00,0x00,0x00,0x00,0x00}, /* ' */\n"
    "    {0x0C,0x18,0x30,0x30,0x30,0x18,0x0C,0x00}, /* ( */\n"
    "    {0x30,0x18,0x0C,0x0C,0x0C,0x18,0x30,0x00}, /* ) */\n"
    "    {0x00,0x66,0x3C,0xFF,0x3C,0x66,0x00,0x00}, /* * */\n"
    "    {0x00,0x18,0x18,0x7E,0x18,0x18,0x00,0x00}, /* + */\n"
    "    {0x00,0x00,0x00,0x00,0x00,0x18,0x18,0x30}, /* , */\n"
    "    {0x00,0x00,0x00,0x7E,0x00,0x00,0x00,0x00}, /* - */\n"
    "    {0x00,0x00,0x00,0x00,0x00,0x30,0x30,0x00}, /* . */\n"
    "    {0x03,0x06,0x0C,0x18,0x30,0x60,0xC0,0x00}, /* / */\n"
    "    {0x7C,0xC6,0xCE,0xD6,0xE6,0xC6,0x7C,0x00}, /* 0 */\n"
    "    {0x18,0x38,0x18,0x18,0x18,0x18,0x7E,0x00}, /* 1 */\n"
    "    {0x7C,0xC6,0x06,0x1C,0x30,0x66,0xFE,0x00}, /* 2 */\n"
    "    {0xFC,0x06,0x06,0x3C,0x06,0x06,0xFC,0x00}, /* 3 */\n"
    "    {0x1C,0x3C,0x6C,0xCC,0xFE,0x0C,0x0C,0x00}, /* 4 */\n"
    "    {0xFE,0xC0,0xFC,0x06,0x06,0xC6,0x7C,0x00}, /* 5 */\n"
    "    {0x3C,0x60,0xC0,0xFC,0xC6,0xC6,0x7C,0x00}, /* 6 */\n"
    "    {0xFE,0xC6,0x0C,0x18,0x30,0x30,0x30,0x00}, /* 7 */\n"
    "    {0x7C,0xC6,0xC6,0x7C,0xC6,0xC6,0x7C,0x00}, /* 8 */\n"
    "    {0x7C,0xC6,0xC6,0x7E,0x06,0x0C,0x78,0x00}, /* 9 */\n"
    "    {0x00,0x30,0x30,0x00,0x00,0x30,0x30,0x00}, /* : */\n"
    "    {0x00,0x30,0x30,0x00,0x00,0x30,0x30,0x60}, /* ; */\n"
    "    {0x0C,0x18,0x30,0x60,0x30,0x18,0x0C,0x00}, /* < */\n"
    "    {0x00,0x00,0x7E,0x00,0x7E,0x00,0x00,0x00}, /* = */\n"
    "    {0x60,0x30,0x18,0x0C,0x18,0x30,0x60,0x00}, /* > */\n"
    "    {0x7C,0xC6,0x06,0x0C,0x18,0x00,0x18,0x00}, /* ? */\n"
    "    {0x7C,0xC6,0xDE,0xDE,0xDC,0xC0,0x7C,0x00}, /* @ */\n"
    "    {0x38,0x6C,0xC6,0xC6,0xFE,0xC6,0xC6,0x00}, /* A */\n"
    "    {0xFC,0xC6,0xC6,0xFC,0xC6,0xC6,0xFC,0x00}, /* B */\n"
    "    {0x7C,0xC6,0xC0,0xC0,0xC0,0xC6,0x7C,0x00}, /* C */\n"
    "    {0xF8,0xCC,0xC6,0xC6,0xC6,0xCC,0xF8,0x00}, /* D */\n"
    "    {0xFE,0xC0,0xC0,0xF8,0xC0,0xC0,0xFE,0x00}, /* E */\n"
    "    {0xFE,0xC0,0xC0,0xF8,0xC0,0xC0,0xC0,0x00}, /* F */\n"
    "    {0x7C,0xC6,0xC0,0xC0,0xCE,0xC6,0x7C,0x00}, /* G */\n"
    "    {0xC6,0xC6,0xC6,0xFE,0xC6,0xC6,0xC6,0x00}, /* H */\n"
    "    {0x7E,0x18,0x18,0x18,0x18,0x18,0x7E,0x00}, /* I */\n"
    "    {0x1E,0x06,0x06,0x06,0xC6,0xC6,0x7C,0x00}, /* J */\n"
    "    {0xC6,0xCC,0xD8,0xF0,0xD8,0xCC,0xC6,0x00}, /* K */\n"
    "    {0xC0,0xC0,0xC0,0xC0,0xC0,0xC0,0xFE,0x00}, /* L */\n"
    "    {0xC6,0xEE,0xFE,0xFE,0xD6,0xC6,0xC6,0x00}, /* M */\n"
    "    {0xC6,0xE6,0xF6,0xDE,0xCE,0xC6,0xC6,0x00}, /* N */\n"
    "    {0x7C,0xC6,0xC6,0xC6,0xC6,0xC6,0x7C,0x00}, /* O */\n"
    "    {0xFC,0xC6,0xC6,0xFC,0xC0,0xC0,0xC0,0x00}, /* P */\n"
    "    {0x7C,0xC6,0xC6,0xC6,0xD6,0xCC,0x76,0x00}, /* Q */\n"
    "    {0xFC,0xC6,0xC6,0xFC,0xCC,0xC6,0xC6,0x00}, /* R */\n"
    "    {0x7C,0xC6,0xC0,0x7C,0x06,0xC6,0x7C,0x00}, /* S */\n"
    "    {0x7E,0x18,0x18,0x18,0x18,0x18,0x18,0x00}, /* T */\n"
    "    {0xC6,0xC6,0xC6,0xC6,0xC6,0xC6,0x7C,0x00}, /* U */\n"
    "    {0xC6,0xC6,0xC6,0xC6,0xC6,0x6C,0x38,0x00}, /* V */\n"
    "    {0xC6,0xC6,0xD6,0xD6,0xFE,0xEE,0xC6,0x00}, /* W */\n"
    "    {0xC6,0xC6,0x6C,0x38,0x6C,0xC6,0xC6,0x00}, /* X */\n"
    "    {0xC6,0xC6,0x6C,0x38,0x18,0x18,0x18,0x00}, /* Y */\n"
    "    {0xFE,0x06,0x0C,0x18,0x30,0x60,0xFE,0x00}, /* Z */\n"
    "    {0x78,0x60,0x60,0x60,0x60,0x60,0x78,0x00}, /* [ */\n"
    "    {0xC0,0x60,0x30,0x18,0x0C,0x06,0x03,0x00}, /* \\ */\n"
    "    {0x78,0x18,0x18,0x18,0x18,0x18,0x78,0x00}, /* ] */\n"
    "    {0x10,0x38,0x6C,0xC6,0x00,0x00,0x00,0x00}, /* ^ */\n"
    "    {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xFF}, /* _ */\n"
    "    {0x18,0x18,0x0C,0x00,0x00,0x00,0x00,0x00}, /* ` */\n"
    "    {0x00,0x00,0x7C,0x06,0x7E,0xC6,0x7E,0x00}, /* a */\n"
    "    {0xC0,0xC0,0xFC,0xC6,0xC6,0xC6,0xFC,0x00}, /* b */\n"
    "    {0x00,0x00,0x7C,0xC6,0xC0,0xC6,0x7C,0x00}, /* c */\n"
    "    {0x06,0x06,0x7E,0xC6,0xC6,0xC6,0x7E,0x00}, /* d */\n"
    "    {0x00,0x00,0x7C,0xC6,0xFE,0xC0,0x7C,0x00}, /* e */\n"
    "    {0x1E,0x30,0x7C,0x30,0x30,0x30,0x30,0x00}, /* f */\n"
    "    {0x00,0x00,0x7E,0xC6,0xC6,0x7E,0x06,0x7C}, /* g */\n"
    "    {0xC0,0xC0,0xFC,0xC6,0xC6,0xC6,0xC6,0x00}, /* h */\n"
    "    {0x18,0x00,0x38,0x18,0x18,0x18,0x3C,0x00}, /* i */\n"
    "    {0x06,0x00,0x06,0x06,0x06,0xC6,0xC6,0x7C}, /* j */\n"
    "    {0xC0,0xC0,0xC6,0xCC,0xD8,0xCC,0xC6,0x00}, /* k */\n"
    "    {0x38,0x18,0x18,0x18,0x18,0x18,0x3C,0x00}, /* l */\n"
    "    {0x00,0x00,0xCC,0xFE,0xFE,0xD6,0xC6,0x00}, /* m */\n"
    "    {0x00,0x00,0xFC,0xC6,0xC6,0xC6,0xC6,0x00}, /* n */\n"
    "    {0x00,0x00,0x7C,0xC6,0xC6,0xC6,0x7C,0x00}, /* o */\n"
    "    {0x00,0x00,0xFC,0xC6,0xC6,0xFC,0xC0,0xC0}, /* p */\n"
    "    {0x00,0x00,0x7E,0xC6,0xC6,0x7E,0x06,0x06}, /* q */\n"
    "    {0x00,0x00,0xDC,0xE6,0xC0,0xC0,0xC0,0x00}, /* r */\n"
    "    {0x00,0x00,0x7C,0xC0,0x7C,0x06,0xFC,0x00}, /* s */\n"
    "    {0x30,0x30,0xFE,0x30,0x30,0x30,0x1E,0x00}, /* t */\n"
    "    {0x00,0x00,0xC6,0xC6,0xC6,0xC6,0x7E,0x00}, /* u */\n"
    "    {0x00,0x00,0xC6,0xC6,0xC6,0x6C,0x38,0x00}, /* v */\n"
    "    {0x00,0x00,0xC6,0xD6,0xFE,0xFE,0x6C,0x00}, /* w */\n"
    "    {0x00,0x00,0xC6,0x6C,0x38,0x6C,0xC6,0x00}, /* x */\n"
    "    {0x00,0x00,0xC6,0xC6,0xC6,0x7E,0x06,0xFC}, /* y */\n"
    "    {0x00,0x00,0xFE,0x0C,0x18,0x30,0xFE,0x00}, /* z */\n"
    "    {0x0E,0x18,0x18,0x70,0x18,0x18,0x0E,0x00}, /* { */\n"
    "    {0x18,0x18,0x18,0x18,0x18,0x18,0x18,0x00}, /* | */\n"
    "    {0x70,0x18,0x18,0x0E,0x18,0x18,0x70,0x00}, /* } */\n"
    "    {0x76,0xDC,0x00,0x00,0x00,0x00,0x00,0x00}, /* ~ */\n"
    "};\n"
    "\n"
    "/* ── global state ───────────────────────────────────────────────── */\n"
    "static struct {\n"
    "    SDL_Window*   win    = nullptr;\n"
    "    SDL_Renderer* ren    = nullptr;\n"
    "    bool          quit   = false;\n"
    "    int           target_fps = 0;\n"
    "    uint64_t      freq = 0, prev = 0;\n"
    "    float         dt = 0.0f;\n"
    "    int           fps = 0;\n"
    "    uint8_t  key_cur[SDL_NUM_SCANCODES]  = {};\n"
    "    uint8_t  key_prev[SDL_NUM_SCANCODES] = {};\n"
    "    uint32_t mouse_cur = 0, mouse_prev = 0;\n"
    "    float    mx = 0, my = 0, mdx = 0, mdy = 0, scroll = 0;\n"
    "    char     last_char = 0;\n"
    "    /* camera 2D */\n"
    "    float cam_tx = 0.0f, cam_ty = 0.0f;\n"
    "    float cam_ox = 0.0f, cam_oy = 0.0f;\n"
    "    float cam_zoom = 1.0f;\n"
    "    /* gamepad (slots 0-3) */\n"
    "    SDL_GameController* pads[4]  = {};\n"
    "    uint8_t pad_btn_cur[4][SDL_CONTROLLER_BUTTON_MAX]  = {};\n"
    "    uint8_t pad_btn_prev[4][SDL_CONTROLLER_BUTTON_MAX] = {};\n"
    "    int16_t pad_axis[4][SDL_CONTROLLER_AXIS_MAX]       = {};\n"
    "} _mk;\n"
    "\n"
    "/* ── camera coordinate helpers (identity when zoom=1, target/offset=0) */\n"
    "static inline float _mk_cx(float x) { return (x - _mk.cam_tx) * _mk.cam_zoom + _mk.cam_ox; }\n"
    "static inline float _mk_cy(float y) { return (y - _mk.cam_ty) * _mk.cam_zoom + _mk.cam_oy; }\n"
    "static inline float _mk_cs(float s) { return s * _mk.cam_zoom; }\n"
    "\n"
    "/* ── window & core loop ─────────────────────────────────────────── */\n"
    "static inline bool _olrn_mk_init_window(int32_t w, int32_t h, const std::string& title) {\n"
    "    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMECONTROLLER) != 0) return false;\n"
    "    _mk.win = SDL_CreateWindow(title.c_str(), SDL_WINDOWPOS_CENTERED,\n"
    "                               SDL_WINDOWPOS_CENTERED, w, h, 0);\n"
    "    if (!_mk.win) { SDL_Quit(); return false; }\n"
    "    _mk.ren = SDL_CreateRenderer(_mk.win, -1, 0);\n"
    "    if (!_mk.ren) { SDL_DestroyWindow(_mk.win); SDL_Quit(); return false; }\n"
    "    SDL_SetRenderDrawBlendMode(_mk.ren, SDL_BLENDMODE_BLEND);\n"
    "    _mk.freq = SDL_GetPerformanceFrequency();\n"
    "    _mk.prev = SDL_GetPerformanceCounter();\n"
    "    for (int i = 0; i < SDL_NumJoysticks() && i < 4; i++)\n"
    "        if (SDL_IsGameController(i)) _mk.pads[i] = SDL_GameControllerOpen(i);\n"
    "    return true; }\n"
    "static inline void _olrn_mk_close_window() {\n"
    "    for (int i = 0; i < 4; i++)\n"
    "        if (_mk.pads[i]) { SDL_GameControllerClose(_mk.pads[i]); _mk.pads[i] = nullptr; }\n"
    "    if (_mk.ren) SDL_DestroyRenderer(_mk.ren);\n"
    "    if (_mk.win) SDL_DestroyWindow(_mk.win);\n"
    "    _mk.ren = nullptr; _mk.win = nullptr;\n"
    "    SDL_Quit(); }\n"
    "static inline bool _olrn_mk_should_close() {\n"
    "    memcpy(_mk.key_prev, _mk.key_cur, SDL_NUM_SCANCODES);\n"
    "    _mk.mouse_prev = _mk.mouse_cur;\n"
    "    _mk.scroll = 0; _mk.last_char = 0;\n"
    "    for (int i = 0; i < 4; i++)\n"
    "        if (_mk.pads[i]) memcpy(_mk.pad_btn_prev[i], _mk.pad_btn_cur[i], SDL_CONTROLLER_BUTTON_MAX);\n"
    "    SDL_Event e;\n"
    "    while (SDL_PollEvent(&e)) {\n"
    "        if      (e.type == SDL_QUIT)        _mk.quit = true;\n"
    "        else if (e.type == SDL_MOUSEWHEEL)  _mk.scroll += (float)e.wheel.y;\n"
    "        else if (e.type == SDL_TEXTINPUT)   _mk.last_char = e.text.text[0];\n"
    "        else if (e.type == SDL_CONTROLLERDEVICEADDED) {\n"
    "            int di = e.cdevice.which;\n"
    "            if (SDL_IsGameController(di))\n"
    "                for (int i = 0; i < 4; i++)\n"
    "                    if (!_mk.pads[i]) { _mk.pads[i] = SDL_GameControllerOpen(di); break; }\n"
    "        } else if (e.type == SDL_CONTROLLERDEVICEREMOVED) {\n"
    "            SDL_JoystickID jid = e.cdevice.which;\n"
    "            for (int i = 0; i < 4; i++) {\n"
    "                if (!_mk.pads[i]) continue;\n"
    "                if (SDL_JoystickInstanceID(SDL_GameControllerGetJoystick(_mk.pads[i])) == jid) {\n"
    "                    SDL_GameControllerClose(_mk.pads[i]); _mk.pads[i] = nullptr;\n"
    "                    memset(_mk.pad_btn_cur[i],  0, SDL_CONTROLLER_BUTTON_MAX);\n"
    "                    memset(_mk.pad_btn_prev[i], 0, SDL_CONTROLLER_BUTTON_MAX);\n"
    "                    memset(_mk.pad_axis[i],     0, SDL_CONTROLLER_AXIS_MAX * sizeof(int16_t));\n"
    "                }\n"
    "            }\n"
    "        }\n"
    "    }\n"
    "    int nk = 0; const Uint8* ks = SDL_GetKeyboardState(&nk);\n"
    "    memcpy(_mk.key_cur, ks, nk < SDL_NUM_SCANCODES ? nk : SDL_NUM_SCANCODES);\n"
    "    int mx2, my2; _mk.mouse_cur = SDL_GetMouseState(&mx2, &my2);\n"
    "    _mk.mdx = (float)mx2 - _mk.mx; _mk.mdy = (float)my2 - _mk.my;\n"
    "    _mk.mx = (float)mx2; _mk.my = (float)my2;\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        if (!_mk.pads[i]) continue;\n"
    "        for (int b = 0; b < SDL_CONTROLLER_BUTTON_MAX; b++)\n"
    "            _mk.pad_btn_cur[i][b] = SDL_GameControllerGetButton(_mk.pads[i], (SDL_GameControllerButton)b);\n"
    "        for (int a = 0; a < SDL_CONTROLLER_AXIS_MAX; a++)\n"
    "            _mk.pad_axis[i][a] = SDL_GameControllerGetAxis(_mk.pads[i], (SDL_GameControllerAxis)a);\n"
    "    }\n"
    "    return _mk.quit; }\n"
    "static inline void _olrn_mk_begin_draw() { (void)0; }\n"
    "static inline void _olrn_mk_end_draw() {\n"
    "    SDL_RenderPresent(_mk.ren);\n"
    "    if (_mk.target_fps > 0) {\n"
    "        uint64_t tgt = _mk.freq / (uint64_t)_mk.target_fps;\n"
    "        while (SDL_GetPerformanceCounter() - _mk.prev < tgt) SDL_Delay(1);\n"
    "    }\n"
    "    uint64_t now = SDL_GetPerformanceCounter();\n"
    "    _mk.dt  = (float)(now - _mk.prev) / (float)_mk.freq;\n"
    "    _mk.fps = _mk.dt > 0.0f ? (int)(1.0f / _mk.dt + 0.5f) : 0;\n"
    "    _mk.prev = now; }\n"
    "static inline void  _olrn_mk_clear_bg(Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    SDL_RenderClear(_mk.ren); }\n"
    "static inline void    _olrn_mk_set_fps(int32_t n)  { _mk.target_fps = n; }\n"
    "static inline float   _olrn_mk_dt()                { return _mk.dt; }\n"
    "static inline int32_t _olrn_mk_fps()               { return _mk.fps; }\n"
    "static inline void    _olrn_mk_set_vsync(bool on)  {\n"
    "#if SDL_VERSION_ATLEAST(2, 0, 18)\n"
    "    SDL_RenderSetVSync(_mk.ren, on ? 1 : 0);\n"
    "#else\n"
    "    (void)on;\n"
    "#endif\n"
    "}\n"
    "static inline void    _olrn_mk_set_title(const std::string& t) {\n"
    "    SDL_SetWindowTitle(_mk.win, t.c_str()); }\n"
    "static inline void    _olrn_mk_fullscreen(bool on) {\n"
    "    SDL_SetWindowFullscreen(_mk.win, on ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0); }\n"
    "static inline int32_t _olrn_mk_width()  { int w,h; SDL_GetWindowSize(_mk.win,&w,&h); return w; }\n"
    "static inline int32_t _olrn_mk_height() { int w,h; SDL_GetWindowSize(_mk.win,&w,&h); return h; }\n"
    "\n"
    "/* ── keyboard ───────────────────────────────────────────────────── */\n"
    "static inline bool _olrn_mk_key_down(int32_t k)     { return _mk.key_cur[k] != 0; }\n"
    "static inline bool _olrn_mk_key_pressed(int32_t k)  { return _mk.key_cur[k] && !_mk.key_prev[k]; }\n"
    "static inline bool _olrn_mk_key_released(int32_t k) { return !_mk.key_cur[k] && _mk.key_prev[k]; }\n"
    "static inline std::string _olrn_mk_key_char() {\n"
    "    return _mk.last_char ? std::string(1, _mk.last_char) : std::string(); }\n"
    "\n"
    "/* ── mouse ──────────────────────────────────────────────────────── */\n"
    "static inline Vec2  _olrn_mk_mouse_pos()             { return Vec2{_mk.mx,_mk.my}; }\n"
    "static inline Vec2  _olrn_mk_mouse_delta()           { return Vec2{_mk.mdx,_mk.mdy}; }\n"
    "static inline float _olrn_mk_mouse_scroll()          { return _mk.scroll; }\n"
    "static inline bool  _olrn_mk_mouse_btn(int32_t b)    { return (_mk.mouse_cur  & SDL_BUTTON(b)) != 0; }\n"
    "static inline bool  _olrn_mk_mouse_btn_pressed(int32_t b) {\n"
    "    return (_mk.mouse_cur & SDL_BUTTON(b)) && !(_mk.mouse_prev & SDL_BUTTON(b)); }\n"
    "static inline bool  _olrn_mk_mouse_btn_released(int32_t b) {\n"
    "    return !(_mk.mouse_cur & SDL_BUTTON(b)) && (_mk.mouse_prev & SDL_BUTTON(b)); }\n"
    "static inline void  _olrn_mk_mouse_set_pos(Vec2 p) {\n"
    "    SDL_WarpMouseInWindow(_mk.win, (int)p.x, (int)p.y); }\n"
    "static inline void  _olrn_mk_mouse_hide() { SDL_ShowCursor(SDL_DISABLE); }\n"
    "static inline void  _olrn_mk_mouse_show() { SDL_ShowCursor(SDL_ENABLE); }\n"
    "\n"
    "/* ── gamepad ────────────────────────────────────────────────────── */\n"
    "static inline bool  _olrn_mk_pad_connected(int32_t id) {\n"
    "    return id >= 0 && id < 4 && _mk.pads[id] != nullptr; }\n"
    "static inline bool  _olrn_mk_pad_btn(int32_t id, int32_t btn) {\n"
    "    if (id < 0 || id >= 4 || btn < 0 || btn >= SDL_CONTROLLER_BUTTON_MAX) return false;\n"
    "    return _mk.pad_btn_cur[id][btn] != 0; }\n"
    "static inline bool  _olrn_mk_pad_btn_pressed(int32_t id, int32_t btn) {\n"
    "    if (id < 0 || id >= 4 || btn < 0 || btn >= SDL_CONTROLLER_BUTTON_MAX) return false;\n"
    "    return _mk.pad_btn_cur[id][btn] && !_mk.pad_btn_prev[id][btn]; }\n"
    "static inline float _olrn_mk_pad_axis(int32_t id, int32_t axis) {\n"
    "    if (id < 0 || id >= 4 || axis < 0 || axis >= SDL_CONTROLLER_AXIS_MAX) return 0.0f;\n"
    "    int16_t v = _mk.pad_axis[id][axis];\n"
    "    return v < 0 ? (float)v / 32768.0f : (float)v / 32767.0f; }\n"
    "\n"
    "/* ── 2D drawing (all positions/sizes in world space; camera applied) */\n"
    "static inline void _olrn_mk_draw_rect(float x, float y, float w, float h, Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    SDL_FRect r{_mk_cx(x), _mk_cy(y), _mk_cs(w), _mk_cs(h)};\n"
    "    SDL_RenderFillRectF(_mk.ren, &r); }\n"
    "static inline void _olrn_mk_draw_rect_lines(float x, float y, float w, float h, float t, Color c) {\n"
    "    _olrn_mk_draw_rect(x,       y,           w, t, c);\n"
    "    _olrn_mk_draw_rect(x,       y + h - t,   w, t, c);\n"
    "    _olrn_mk_draw_rect(x,       y + t,        t, h - 2*t, c);\n"
    "    _olrn_mk_draw_rect(x + w - t, y + t,      t, h - 2*t, c); }\n"
    "static inline void _olrn_mk_draw_rect_rot(float x, float y, float w, float h,\n"
    "                                           Vec2 origin, float rot_deg, Color c) {\n"
    "    float rad = rot_deg * 3.14159265f / 180.0f;\n"
    "    float ca = SDL_cosf(rad), sa = SDL_sinf(rad);\n"
    "    float lx[4] = {-origin.x, w-origin.x, w-origin.x, -origin.x};\n"
    "    float ly[4] = {-origin.y, -origin.y,   h-origin.y,  h-origin.y};\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex v[4];\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        float rx = lx[i]*ca - ly[i]*sa;\n"
    "        float ry = lx[i]*sa + ly[i]*ca;\n"
    "        v[i] = {{_mk_cx(x+rx), _mk_cy(y+ry)}, sc, {0,0}};\n"
    "    }\n"
    "    int idx[6] = {0,1,2,0,2,3};\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, v, 4, idx, 6); }\n"
    "static inline void _olrn_mk_draw_line(float x1, float y1, float x2, float y2, float t, Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    if (_mk_cs(t) <= 1.0f) {\n"
    "        SDL_RenderDrawLineF(_mk.ren, _mk_cx(x1), _mk_cy(y1), _mk_cx(x2), _mk_cy(y2)); return;\n"
    "    }\n"
    "    float dx = x2-x1, dy = y2-y1;\n"
    "    float len = SDL_sqrtf(dx*dx + dy*dy);\n"
    "    if (len <= 0.0f) return;\n"
    "    float ht = _mk_cs(t) * 0.5f;\n"
    "    float px = -dy/len * ht, py = dx/len * ht;\n"
    "    float sx1=_mk_cx(x1), sy1=_mk_cy(y1), sx2=_mk_cx(x2), sy2=_mk_cy(y2);\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex vv[4] = {\n"
    "        {{sx1+px,sy1+py},sc,{0,0}}, {{sx1-px,sy1-py},sc,{0,0}},\n"
    "        {{sx2-px,sy2-py},sc,{0,0}}, {{sx2+px,sy2+py},sc,{0,0}} };\n"
    "    int idx[6] = {0,1,2,0,2,3};\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, vv, 4, idx, 6); }\n"
    "static inline void _olrn_mk_draw_fan(float cx, float cy, float r, int n, float rot, Color c) {\n"
    "    if (n < 3) n = 3;\n"
    "    if (n > 128) n = 128;\n"
    "    float scx=_mk_cx(cx), scy=_mk_cy(cy), sr=_mk_cs(r);\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex vv[130]; int idx[128*3];\n"
    "    vv[0] = {{scx, scy}, sc, {0,0}};\n"
    "    for (int i = 0; i <= n; i++) {\n"
    "        float a = rot + (float)i/(float)n * 6.28318530718f;\n"
    "        vv[i+1] = {{scx + SDL_cosf(a)*sr, scy + SDL_sinf(a)*sr}, sc, {0,0}};\n"
    "    }\n"
    "    for (int i = 0; i < n; i++) { idx[i*3]=0; idx[i*3+1]=i+1; idx[i*3+2]=i+2; }\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, vv, n+2, idx, n*3); }\n"
    "static inline void _olrn_mk_draw_circle(float cx, float cy, float r, Color c) {\n"
    "    int n = (int)(r * 0.8f); if (n < 12) n = 12; if (n > 64) n = 64;\n"
    "    _olrn_mk_draw_fan(cx, cy, r, n, 0.0f, c); }\n"
    "static inline void _olrn_mk_draw_circle_lines(float cx, float cy, float r, Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    int n = (int)(r * 0.8f); if (n < 12) n = 12; if (n > 64) n = 64;\n"
    "    float scx=_mk_cx(cx), scy=_mk_cy(cy), sr=_mk_cs(r);\n"
    "    float px = scx+sr, py = scy;\n"
    "    for (int i = 1; i <= n; i++) {\n"
    "        float a = (float)i/(float)n * 6.28318530718f;\n"
    "        float nx = scx+SDL_cosf(a)*sr, ny = scy+SDL_sinf(a)*sr;\n"
    "        SDL_RenderDrawLineF(_mk.ren, px, py, nx, ny);\n"
    "        px = nx; py = ny;\n"
    "    } }\n"
    "static inline void _olrn_mk_draw_tri(Vec2 a, Vec2 b, Vec2 cc, Color c) {\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex vv[3] = {\n"
    "        {{_mk_cx(a.x),_mk_cy(a.y)},sc,{0,0}},\n"
    "        {{_mk_cx(b.x),_mk_cy(b.y)},sc,{0,0}},\n"
    "        {{_mk_cx(cc.x),_mk_cy(cc.y)},sc,{0,0}} };\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, vv, 3, nullptr, 0); }\n"
    "static inline void _olrn_mk_draw_poly(Vec2 center, int32_t sides, float r, float rot, Color c) {\n"
    "    _olrn_mk_draw_fan(center.x, center.y, r, sides, rot, c); }\n"
    "\n"
    "/* ── textures ───────────────────────────────────────────────────── */\n"
    "static inline int64_t _olrn_mk_load_texture(const std::string& path) {\n"
    "    SDL_Surface* s = SDL_LoadBMP(path.c_str());\n"
    "    if (!s) return 0;\n"
    "    SDL_Texture* t = SDL_CreateTextureFromSurface(_mk.ren, s);\n"
    "    SDL_FreeSurface(s);\n"
    "    return (int64_t)(uintptr_t)t; }\n"
    "static inline void _olrn_mk_unload_texture(int64_t t) {\n"
    "    if (t) SDL_DestroyTexture((SDL_Texture*)(uintptr_t)t); }\n"
    "static inline void _olrn_mk_draw_texture(int64_t t, float x, float y, Color tint) {\n"
    "    SDL_Texture* tex = (SDL_Texture*)(uintptr_t)t;\n"
    "    int w,h; SDL_QueryTexture(tex, nullptr, nullptr, &w, &h);\n"
    "    SDL_SetTextureColorMod(tex, tint.r, tint.g, tint.b);\n"
    "    SDL_SetTextureAlphaMod(tex, tint.a);\n"
    "    SDL_FRect dst{_mk_cx(x), _mk_cy(y), _mk_cs((float)w), _mk_cs((float)h)};\n"
    "    SDL_RenderCopyF(_mk.ren, tex, nullptr, &dst); }\n"
    "static inline void _olrn_mk_draw_texture_ex(int64_t t, Vec2 pos, float rot, float scale, Color tint) {\n"
    "    SDL_Texture* tex = (SDL_Texture*)(uintptr_t)t;\n"
    "    int w,h; SDL_QueryTexture(tex, nullptr, nullptr, &w, &h);\n"
    "    SDL_SetTextureColorMod(tex, tint.r, tint.g, tint.b);\n"
    "    SDL_SetTextureAlphaMod(tex, tint.a);\n"
    "    SDL_FRect dst{_mk_cx(pos.x), _mk_cy(pos.y), _mk_cs((float)w*scale), _mk_cs((float)h*scale)};\n"
    "    SDL_RenderCopyExF(_mk.ren, tex, nullptr, &dst, rot, nullptr, SDL_FLIP_NONE); }\n"
    "static inline void _olrn_mk_draw_texture_rect(int64_t t, Rect src, Rect dst, Color tint) {\n"
    "    SDL_Texture* tex = (SDL_Texture*)(uintptr_t)t;\n"
    "    SDL_SetTextureColorMod(tex, tint.r, tint.g, tint.b);\n"
    "    SDL_SetTextureAlphaMod(tex, tint.a);\n"
    "    SDL_Rect  srect{(int)src.x,(int)src.y,(int)src.w,(int)src.h};\n"
    "    SDL_FRect drect{_mk_cx(dst.x),_mk_cy(dst.y),_mk_cs(dst.w),_mk_cs(dst.h)};\n"
    "    SDL_RenderCopyF(_mk.ren, tex, &srect, &drect); }\n"
    "\n"
    "/* ── camera 2D ──────────────────────────────────────────────────── */\n"
    "static inline void _olrn_mk_begin_camera2d(Camera2D cam) {\n"
    "    _mk.cam_tx = cam.target.x; _mk.cam_ty = cam.target.y;\n"
    "    _mk.cam_ox = cam.offset.x; _mk.cam_oy = cam.offset.y;\n"
    "    _mk.cam_zoom = cam.zoom > 0.0f ? cam.zoom : 1.0f; }\n"
    "static inline void _olrn_mk_end_camera2d() {\n"
    "    _mk.cam_tx = 0.0f; _mk.cam_ty = 0.0f;\n"
    "    _mk.cam_ox = 0.0f; _mk.cam_oy = 0.0f;\n"
    "    _mk.cam_zoom = 1.0f; }\n"
    "static inline Vec2 _olrn_mk_screen_to_world2d(Vec2 pos, Camera2D cam) {\n"
    "    float z = cam.zoom > 0.0f ? cam.zoom : 1.0f;\n"
    "    return Vec2{(pos.x - cam.offset.x)/z + cam.target.x,\n"
    "                (pos.y - cam.offset.y)/z + cam.target.y}; }\n"
    "static inline Vec2 _olrn_mk_world_to_screen2d(Vec2 pos, Camera2D cam) {\n"
    "    float z = cam.zoom > 0.0f ? cam.zoom : 1.0f;\n"
    "    return Vec2{(pos.x - cam.target.x)*z + cam.offset.x,\n"
    "                (pos.y - cam.target.y)*z + cam.offset.y}; }\n"
    "\n"
    "/* ── text (embedded 8x8 bitmap font) ────────────────────────────── */\n"
    "static inline void _olrn_mk_draw_text(const std::string& text, float x, float y,\n"
    "                                       float size, Color c) {\n"
    "    float scale = size / 8.0f;\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    float gx = x;\n"
    "    for (unsigned char ch : text) {\n"
    "        if (ch < 32 || ch > 126) { gx += size; continue; }\n"
    "        const uint8_t* g = _mk_font8[ch - 32];\n"
    "        for (int row = 0; row < 8; row++) {\n"
    "            uint8_t bits = g[row];\n"
    "            if (!bits) continue;\n"
    "            for (int col = 0; col < 8; col++) {\n"
    "                if (!(bits & (0x80 >> col))) continue;\n"
    "                float ps = _mk_cs(scale); if (ps < 1.0f) ps = 1.0f;\n"
    "                SDL_FRect r{_mk_cx(gx + col*scale), _mk_cy(y + row*scale), ps, ps};\n"
    "                SDL_RenderFillRectF(_mk.ren, &r);\n"
    "            }\n"
    "        }\n"
    "        gx += size;\n"
    "    } }\n"
    "static inline Vec2 _olrn_mk_measure_text(const std::string& text, float size) {\n"
    "    return Vec2{(float)text.size() * size, size}; }\n"
    "/* ── end malkur ─────────────────────────────────────────────────── */\n";

#endif /* OLRN_MALKUR_IMPL_H */
