#ifndef OLRN_MALKUR_IMPL_H
#define OLRN_MALKUR_IMPL_H

/* C++ implementation injected when @std.malkur is imported.
   SDL2 backend; window/renderer/input live in one global state blob
   (Raylib-style). All helpers use the _olrn_mk_ prefix. */
static const char *MALKUR_IMPL =
    "/* ── malkur gamedev library (SDL2 backend) ─────────────────────── */\n"
    "#include <SDL2/SDL.h>\n"
    "\n"
    "struct Color { uint8_t r, g, b, a; };\n"
    "struct Vec2  { float x, y; };\n"
    "struct Rect  { float x, y, w, h; };\n"
    "\n"
    "static struct {\n"
    "    SDL_Window*   win = nullptr;\n"
    "    SDL_Renderer* ren = nullptr;\n"
    "    bool     quit = false;\n"
    "    int      target_fps = 0;\n"
    "    uint64_t freq = 0, prev = 0;\n"
    "    float    dt = 0.0f;\n"
    "    int      fps = 0;\n"
    "    uint8_t  key_cur[SDL_NUM_SCANCODES]  = {0};\n"
    "    uint8_t  key_prev[SDL_NUM_SCANCODES] = {0};\n"
    "    uint32_t mouse_cur = 0, mouse_prev = 0;\n"
    "    float    mx = 0, my = 0, mdx = 0, mdy = 0, scroll = 0;\n"
    "    char     last_char = 0;\n"
    "} _mk;\n"
    "\n"
    "/* window & core loop */\n"
    "static inline bool _olrn_mk_init_window(int32_t w, int32_t h, const std::string& title) {\n"
    "    if (SDL_Init(SDL_INIT_VIDEO) != 0) return false;\n"
    "    _mk.win = SDL_CreateWindow(title.c_str(), SDL_WINDOWPOS_CENTERED,\n"
    "                               SDL_WINDOWPOS_CENTERED, w, h, 0);\n"
    "    if (!_mk.win) { SDL_Quit(); return false; }\n"
    "    _mk.ren = SDL_CreateRenderer(_mk.win, -1, 0);\n"
    "    if (!_mk.ren) { SDL_DestroyWindow(_mk.win); SDL_Quit(); return false; }\n"
    "    SDL_SetRenderDrawBlendMode(_mk.ren, SDL_BLENDMODE_BLEND);\n"
    "    _mk.freq = SDL_GetPerformanceFrequency();\n"
    "    _mk.prev = SDL_GetPerformanceCounter();\n"
    "    return true; }\n"
    "static inline void _olrn_mk_close_window() {\n"
    "    if (_mk.ren) SDL_DestroyRenderer(_mk.ren);\n"
    "    if (_mk.win) SDL_DestroyWindow(_mk.win);\n"
    "    _mk.ren = nullptr; _mk.win = nullptr;\n"
    "    SDL_Quit(); }\n"
    "static inline bool _olrn_mk_should_close() {\n"
    "    SDL_memcpy(_mk.key_prev, _mk.key_cur, SDL_NUM_SCANCODES);\n"
    "    _mk.mouse_prev = _mk.mouse_cur;\n"
    "    _mk.scroll = 0; _mk.last_char = 0;\n"
    "    SDL_Event e;\n"
    "    while (SDL_PollEvent(&e)) {\n"
    "        if (e.type == SDL_QUIT) _mk.quit = true;\n"
    "        else if (e.type == SDL_MOUSEWHEEL) _mk.scroll += (float)e.wheel.y;\n"
    "        else if (e.type == SDL_TEXTINPUT)  _mk.last_char = e.text.text[0];\n"
    "    }\n"
    "    int nk = 0; const Uint8* ks = SDL_GetKeyboardState(&nk);\n"
    "    SDL_memcpy(_mk.key_cur, ks, nk < SDL_NUM_SCANCODES ? nk : SDL_NUM_SCANCODES);\n"
    "    int mx, my; _mk.mouse_cur = SDL_GetMouseState(&mx, &my);\n"
    "    _mk.mdx = (float)mx - _mk.mx; _mk.mdy = (float)my - _mk.my;\n"
    "    _mk.mx = (float)mx; _mk.my = (float)my;\n"
    "    return _mk.quit; }\n"
    "static inline void _olrn_mk_begin_draw() { (void)0; }\n"
    "static inline void _olrn_mk_end_draw() {\n"
    "    SDL_RenderPresent(_mk.ren);\n"
    "    if (_mk.target_fps > 0) {\n"
    "        uint64_t target = _mk.freq / (uint64_t)_mk.target_fps;\n"
    "        while (SDL_GetPerformanceCounter() - _mk.prev < target) SDL_Delay(1);\n"
    "    }\n"
    "    uint64_t now = SDL_GetPerformanceCounter();\n"
    "    _mk.dt  = (float)(now - _mk.prev) / (float)_mk.freq;\n"
    "    _mk.fps = _mk.dt > 0.0f ? (int)(1.0f / _mk.dt + 0.5f) : 0;\n"
    "    _mk.prev = now; }\n"
    "static inline void _olrn_mk_clear_bg(Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    SDL_RenderClear(_mk.ren); }\n"
    "static inline void  _olrn_mk_set_fps(int32_t n)   { _mk.target_fps = n; }\n"
    "static inline float _olrn_mk_dt()                 { return _mk.dt; }\n"
    "static inline int32_t _olrn_mk_fps()              { return _mk.fps; }\n"
    "static inline void  _olrn_mk_set_vsync(bool on)   {\n"
    "#if SDL_VERSION_ATLEAST(2, 0, 18)\n"
    "    SDL_RenderSetVSync(_mk.ren, on ? 1 : 0);\n"
    "#else\n"
    "    (void)on;\n"
    "#endif\n"
    "}\n"
    "static inline void  _olrn_mk_set_title(const std::string& t) {\n"
    "    SDL_SetWindowTitle(_mk.win, t.c_str()); }\n"
    "static inline void  _olrn_mk_fullscreen(bool on)  {\n"
    "    SDL_SetWindowFullscreen(_mk.win, on ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0); }\n"
    "static inline int32_t _olrn_mk_width()  { int w, h; SDL_GetWindowSize(_mk.win, &w, &h); return w; }\n"
    "static inline int32_t _olrn_mk_height() { int w, h; SDL_GetWindowSize(_mk.win, &w, &h); return h; }\n"
    "\n"
    "/* keyboard — args are SDL scancodes (keys enum) */\n"
    "static inline bool _olrn_mk_key_down(int32_t k)     { return _mk.key_cur[k] != 0; }\n"
    "static inline bool _olrn_mk_key_pressed(int32_t k)  { return _mk.key_cur[k] && !_mk.key_prev[k]; }\n"
    "static inline bool _olrn_mk_key_released(int32_t k) { return !_mk.key_cur[k] && _mk.key_prev[k]; }\n"
    "static inline std::string _olrn_mk_key_char() {\n"
    "    return _mk.last_char ? std::string(1, _mk.last_char) : std::string(); }\n"
    "\n"
    "/* mouse — btn args are the mbtn enum (SDL button numbers) */\n"
    "static inline Vec2  _olrn_mk_mouse_pos()    { return Vec2{_mk.mx, _mk.my}; }\n"
    "static inline Vec2  _olrn_mk_mouse_delta()  { return Vec2{_mk.mdx, _mk.mdy}; }\n"
    "static inline float _olrn_mk_mouse_scroll() { return _mk.scroll; }\n"
    "static inline bool _olrn_mk_mouse_btn(int32_t b)          { return (_mk.mouse_cur  & SDL_BUTTON(b)) != 0; }\n"
    "static inline bool _olrn_mk_mouse_btn_pressed(int32_t b)  { return (_mk.mouse_cur & SDL_BUTTON(b)) && !(_mk.mouse_prev & SDL_BUTTON(b)); }\n"
    "static inline bool _olrn_mk_mouse_btn_released(int32_t b) { return !(_mk.mouse_cur & SDL_BUTTON(b)) && (_mk.mouse_prev & SDL_BUTTON(b)); }\n"
    "static inline void _olrn_mk_mouse_set_pos(Vec2 p) { SDL_WarpMouseInWindow(_mk.win, (int)p.x, (int)p.y); }\n"
    "static inline void _olrn_mk_mouse_hide() { SDL_ShowCursor(SDL_DISABLE); }\n"
    "static inline void _olrn_mk_mouse_show() { SDL_ShowCursor(SDL_ENABLE); }\n"
    "\n"
    "/* 2D drawing */\n"
    "static inline void _olrn_mk_draw_rect(float x, float y, float w, float h, Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    SDL_FRect r{x, y, w, h}; SDL_RenderFillRectF(_mk.ren, &r); }\n"
    "static inline void _olrn_mk_draw_rect_lines(float x, float y, float w, float h, float t, Color c) {\n"
    "    _olrn_mk_draw_rect(x, y, w, t, c);\n"
    "    _olrn_mk_draw_rect(x, y + h - t, w, t, c);\n"
    "    _olrn_mk_draw_rect(x, y + t, t, h - 2 * t, c);\n"
    "    _olrn_mk_draw_rect(x + w - t, y + t, t, h - 2 * t, c); }\n"
    "static inline void _olrn_mk_draw_line(float x1, float y1, float x2, float y2, float t, Color c) {\n"
    "    if (t <= 1.0f) {\n"
    "        SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "        SDL_RenderDrawLineF(_mk.ren, x1, y1, x2, y2); return;\n"
    "    }\n"
    "    float dx = x2 - x1, dy = y2 - y1;\n"
    "    float len = SDL_sqrtf(dx * dx + dy * dy);\n"
    "    if (len <= 0.0f) return;\n"
    "    float px = -dy / len * t * 0.5f, py = dx / len * t * 0.5f;\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex v[4] = {\n"
    "        {{x1 + px, y1 + py}, sc, {0, 0}}, {{x1 - px, y1 - py}, sc, {0, 0}},\n"
    "        {{x2 - px, y2 - py}, sc, {0, 0}}, {{x2 + px, y2 + py}, sc, {0, 0}} };\n"
    "    int idx[6] = {0, 1, 2, 0, 2, 3};\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, v, 4, idx, 6); }\n"
    "static inline void _olrn_mk_draw_tri(Vec2 a, Vec2 b, Vec2 cc, Color c) {\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex v[3] = {\n"
    "        {{a.x, a.y}, sc, {0, 0}}, {{b.x, b.y}, sc, {0, 0}}, {{cc.x, cc.y}, sc, {0, 0}} };\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, v, 3, nullptr, 0); }\n"
    "static inline void _olrn_mk_draw_fan(float cx, float cy, float r, int n, float rot, Color c) {\n"
    "    if (n < 3) n = 3; if (n > 128) n = 128;\n"
    "    SDL_Color sc{c.r, c.g, c.b, c.a};\n"
    "    SDL_Vertex v[130]; int idx[128 * 3];\n"
    "    v[0] = {{cx, cy}, sc, {0, 0}};\n"
    "    for (int i = 0; i <= n; i++) {\n"
    "        float a = rot + (float)i / (float)n * 6.28318530718f;\n"
    "        v[i + 1] = {{cx + SDL_cosf(a) * r, cy + SDL_sinf(a) * r}, sc, {0, 0}};\n"
    "    }\n"
    "    for (int i = 0; i < n; i++) { idx[i*3] = 0; idx[i*3+1] = i + 1; idx[i*3+2] = i + 2; }\n"
    "    SDL_RenderGeometry(_mk.ren, nullptr, v, n + 2, idx, n * 3); }\n"
    "static inline void _olrn_mk_draw_circle(float cx, float cy, float r, Color c) {\n"
    "    int n = (int)(r * 0.8f); if (n < 12) n = 12; if (n > 64) n = 64;\n"
    "    _olrn_mk_draw_fan(cx, cy, r, n, 0.0f, c); }\n"
    "static inline void _olrn_mk_draw_circle_lines(float cx, float cy, float r, Color c) {\n"
    "    SDL_SetRenderDrawColor(_mk.ren, c.r, c.g, c.b, c.a);\n"
    "    int n = (int)(r * 0.8f); if (n < 12) n = 12; if (n > 64) n = 64;\n"
    "    float prev_x = cx + r, prev_y = cy;\n"
    "    for (int i = 1; i <= n; i++) {\n"
    "        float a = (float)i / (float)n * 6.28318530718f;\n"
    "        float nx = cx + SDL_cosf(a) * r, ny = cy + SDL_sinf(a) * r;\n"
    "        SDL_RenderDrawLineF(_mk.ren, prev_x, prev_y, nx, ny);\n"
    "        prev_x = nx; prev_y = ny;\n"
    "    } }\n"
    "static inline void _olrn_mk_draw_poly(Vec2 center, int32_t sides, float r, float rot, Color c) {\n"
    "    _olrn_mk_draw_fan(center.x, center.y, r, sides, rot, c); }\n"
    "\n"
    "/* textures — BMP via SDL core; PNG/JPG need SDL_image (later) */\n"
    "static inline int64_t _olrn_mk_load_texture(const std::string& path) {\n"
    "    SDL_Surface* s = SDL_LoadBMP(path.c_str());\n"
    "    if (!s) return 0;\n"
    "    SDL_Texture* t = SDL_CreateTextureFromSurface(_mk.ren, s);\n"
    "    SDL_FreeSurface(s);\n"
    "    return (int64_t)(uintptr_t)t; }\n"
    "static inline void _olrn_mk_unload_texture(int64_t t) {\n"
    "    if (t) SDL_DestroyTexture((SDL_Texture*)(uintptr_t)t); }\n"
    "static inline void _olrn_mk_draw_texture(int64_t t, float x, float y, Color tint) {\n"
    "    SDL_Texture* tex = (SDL_Texture*)(uintptr_t)t;\n"
    "    int w, h; SDL_QueryTexture(tex, nullptr, nullptr, &w, &h);\n"
    "    SDL_SetTextureColorMod(tex, tint.r, tint.g, tint.b);\n"
    "    SDL_SetTextureAlphaMod(tex, tint.a);\n"
    "    SDL_FRect dst{x, y, (float)w, (float)h};\n"
    "    SDL_RenderCopyF(_mk.ren, tex, nullptr, &dst); }\n"
    "static inline void _olrn_mk_draw_texture_ex(int64_t t, Vec2 pos, float rot, float scale, Color tint) {\n"
    "    SDL_Texture* tex = (SDL_Texture*)(uintptr_t)t;\n"
    "    int w, h; SDL_QueryTexture(tex, nullptr, nullptr, &w, &h);\n"
    "    SDL_SetTextureColorMod(tex, tint.r, tint.g, tint.b);\n"
    "    SDL_SetTextureAlphaMod(tex, tint.a);\n"
    "    SDL_FRect dst{pos.x, pos.y, (float)w * scale, (float)h * scale};\n"
    "    SDL_RenderCopyExF(_mk.ren, tex, nullptr, &dst, rot, nullptr, SDL_FLIP_NONE); }\n"
    "/* ── end malkur ─────────────────────────────────────────────────── */\n";

#endif /* OLRN_MALKUR_IMPL_H */
