#ifndef OLRN_STDLIB_IMPL_H
#define OLRN_STDLIB_IMPL_H

/* Always-emitted helpers for language builtins (@cin, @rng). */
static const char *BUILTINS_IMPL =
    "/* ── olrn builtins ─────────────────────────────────────────────── */\n"
    "template<typename T> static inline T _olrn_pf_cvt(T v) { return v; }\n"
    "static inline const char* _olrn_pf_cvt(const std::string& s) { return s.c_str(); }\n"
    "static inline std::string _olrn_cin(const std::string& prompt) {\n"
    "    std::cout << prompt;\n"
    "    std::string _line;\n"
    "    std::getline(std::cin, _line);\n"
    "    return _line; }\n"
    "template<typename T>\n"
    "static inline std::string _olrn_hex(T v) {\n"
    "    char _hbuf[32];\n"
    "    snprintf(_hbuf, sizeof(_hbuf), \"%llx\", (unsigned long long)(uint64_t)v);\n"
    "    return std::string(_hbuf); }\n"
    "/* ── @ls(T) growable list ───────────────────────────────────────── */\n"
    "template<typename T>\n"
    "struct _OlrnList : public std::vector<T> {\n"
    "    using std::vector<T>::vector;\n"
    "    _OlrnList() = default;\n"
    "    explicit _OlrnList(std::vector<T> v) : std::vector<T>(std::move(v)) {} };\n"
    "template<typename T>\n"
    "static inline _OlrnList<T> _olrn_ls_init(int64_t cap) {\n"
    "    _OlrnList<T> v; v.reserve((size_t)cap); return v; }\n"
    "template<typename T>\n"
    "static inline T _olrn_ls_pop(_OlrnList<T>& v) {\n"
    "    T x = std::move(v.back()); v.pop_back(); return x; }\n"
    "template<typename T>\n"
    "static inline T _olrn_rng(T lo, T hi) {\n"
    "    static std::mt19937 _eng(std::random_device{}());\n"
    "    if constexpr (std::is_integral_v<T>)\n"
    "        return std::uniform_int_distribution<T>(lo, hi)(_eng);\n"
    "    else\n"
    "        return std::uniform_real_distribution<T>(lo, hi)(_eng); }\n"
    "/* ── error handling ─────────────────────────────────────────────── */\n"
    "struct _OlrnError { int32_t code; const char* msg; };\n"
    "template<typename T>\n"
    "struct _OlrnResult {\n"
    "    bool _ok; T _val; _OlrnError _err;\n"
    "    _OlrnResult(T v) : _ok(true), _val(std::move(v)), _err{0, nullptr} {}\n"
    "    _OlrnResult(_OlrnError e) : _ok(false), _val{}, _err(e) {}\n"
    "    bool is_ok() const { return _ok; }\n"
    "    T value() const { return _val; }\n"
    "    const _OlrnError& error() const { return _err; }\n"
    "};\n"
    "template<> struct _OlrnResult<void> {\n"
    "    bool _ok; _OlrnError _err;\n"
    "    _OlrnResult() : _ok(true), _err{0, nullptr} {}\n"
    "    _OlrnResult(_OlrnError e) : _ok(false), _err(e) {}\n"
    "    bool is_ok() const { return _ok; }\n"
    "    const _OlrnError& error() const { return _err; }\n"
    "};\n"
    "/* casts: numeric/enum → plain static_cast; string → fallible parse,\n"
    "   so @i32(\"42\") yields _OlrnResult<int32_t> (use try/catch) */\n"
    "template<typename T, typename F,\n"
    "         typename std::enable_if<std::is_arithmetic<F>::value ||\n"
    "                                 std::is_enum<F>::value, int>::type = 0>\n"
    "static inline T _olrn_cast(F v) { return static_cast<T>(v); }\n"
    "template<typename T>\n"
    "static inline _OlrnResult<T> _olrn_cast(const std::string& s) {\n"
    "    try {\n"
    "        size_t pos = 0;\n"
    "        if constexpr (std::is_floating_point_v<T>) {\n"
    "            double d = std::stod(s, &pos);\n"
    "            if (pos != s.size()) return _OlrnError{-1, \"InvalidNumber\"};\n"
    "            return _OlrnResult<T>(static_cast<T>(d));\n"
    "        } else if constexpr (std::is_unsigned_v<T>) {\n"
    "            if (!s.empty() && s[0] == '-') return _OlrnError{-1, \"InvalidNumber\"};\n"
    "            unsigned long long v = std::stoull(s, &pos);\n"
    "            if (pos != s.size()) return _OlrnError{-1, \"InvalidNumber\"};\n"
    "            return _OlrnResult<T>(static_cast<T>(v));\n"
    "        } else {\n"
    "            long long v = std::stoll(s, &pos);\n"
    "            if (pos != s.size()) return _OlrnError{-1, \"InvalidNumber\"};\n"
    "            return _OlrnResult<T>(static_cast<T>(v));\n"
    "        }\n"
    "    } catch (...) { return _OlrnError{-1, \"InvalidNumber\"}; }\n"
    "}\n"
    "template<typename T>\n"
    "static inline _OlrnResult<T> _olrn_cast(const char* s) {\n"
    "    return _olrn_cast<T>(std::string(s)); }\n"
    "static std::string _olrn_map_type(const std::string &s) {\n"
    "    if(s==\"int\"||s==\"int32_t\")  return \"i32\";\n"
    "    if(s==\"long\"||s==\"long long\"||s==\"int64_t\") return \"i64\";\n"
    "    if(s==\"short\"||s==\"int16_t\") return \"i16\";\n"
    "    if(s==\"signed char\"||s==\"int8_t\") return \"i8\";\n"
    "    if(s==\"unsigned int\"||s==\"uint32_t\") return \"u32\";\n"
    "    if(s==\"unsigned long\"||s==\"unsigned long long\"||s==\"uint64_t\") return \"u64\";\n"
    "    if(s==\"unsigned short\"||s==\"uint16_t\") return \"u16\";\n"
    "    if(s==\"unsigned char\"||s==\"uint8_t\") return \"u8\";\n"
    "    if(s==\"float\")  return \"f32\";\n"
    "    if(s==\"double\") return \"f64\";\n"
    "    if(s==\"bool\")   return \"bool\";\n"
    "    if(s==\"char\")   return \"char\";\n"
    "    if(s==\"void\")   return \"void\";\n"
    "    if(s.find(\"basic_string\")!=std::string::npos) return \"str\";\n"
    "    /* raw pointer: ends with * */\n"
    "    if(s.size()>1&&s.back()=='*'){\n"
    "        size_t e=s.size()-1; while(e>0&&s[e-1]==' ')e--;\n"
    "        return \"*\"+_olrn_map_type(s.substr(0,e)); }\n"
    "    /* smart pointer */\n"
    "    if(s.size()>16&&s.compare(0,16,\"std::shared_ptr<\")==0&&s.back()=='>')\n"
    "        return \"^\"+_olrn_map_type(s.substr(16,s.size()-17));\n"
    "    /* @ls list */\n"
    "    if(s.size()>10&&s.compare(0,10,\"_OlrnList<\")==0&&s.back()=='>') {\n"
    "        return \"@ls(\"+_olrn_map_type(s.substr(10,s.size()-11))+\")\"; }\n"
    "    /* slice / dynamic array */\n"
    "    if(s.size()>12&&s.compare(0,12,\"std::vector<\")==0&&s.back()=='>') {\n"
    "        std::string a=s.substr(12,s.size()-13);\n"
    "        int d=0; size_t c=a.size();\n"
    "        for(size_t i=0;i<a.size();i++){\n"
    "            if(a[i]=='<')d++; else if(a[i]=='>')d--;\n"
    "            else if(a[i]==','&&d==0){c=i;break;} }\n"
    "        return \"[]\"+_olrn_map_type(a.substr(0,c)); }\n"
    "    /* fixed array */\n"
    "    if(s.size()>11&&s.compare(0,11,\"std::array<\")==0&&s.back()=='>') {\n"
    "        std::string a=s.substr(11,s.size()-12);\n"
    "        int d=0; size_t c=a.size();\n"
    "        for(size_t i=0;i<a.size();i++){\n"
    "            if(a[i]=='<')d++; else if(a[i]=='>')d--;\n"
    "            else if(a[i]==','&&d==0){c=i;break;} }\n"
    "        if(c<a.size()){\n"
    "            std::string sz=a.substr(c+1);\n"
    "            size_t sl=sz.find_first_not_of(' ');\n"
    "            if(sl!=std::string::npos)sz=sz.substr(sl);\n"
    "            return \"[\"+sz+\"]\"+_olrn_map_type(a.substr(0,c)); } }\n"
    "    return s;\n"
    "}\n"
    "template<typename T>\n"
    "static inline std::string _olrn_type_name(const T& v) {\n"
    "    int st; char *d=abi::__cxa_demangle(typeid(v).name(),nullptr,nullptr,&st);\n"
    "    std::string r=(st==0&&d)?d:typeid(v).name(); free(d);\n"
    "    return _olrn_map_type(r); }\n"
    "/* ── end olrn builtins ──────────────────────────────────────────── */\n";

/* C++ implementations injected when @libs.std is imported.
   All helpers use _olrn_ prefix to avoid collisions. */
static const char *STDLIB_IMPL =
    "/* ── olrn stdlib ───────────────────────────────────────────────── */\n"
    "#include <chrono>\n"
    "#include <thread>\n"
    "#include <mutex>\n"
    "#include <atomic>\n"
    "#include <filesystem>\n"
    "\n"
    "/* std.time */\n"
    "static inline int64_t _olrn_time_now() {\n"
    "    return std::chrono::duration_cast<std::chrono::nanoseconds>(\n"
    "        std::chrono::system_clock::now().time_since_epoch()).count(); }\n"
    "static inline int64_t _olrn_time_mono() {\n"
    "    return std::chrono::duration_cast<std::chrono::nanoseconds>(\n"
    "        std::chrono::steady_clock::now().time_since_epoch()).count(); }\n"
    "static inline void _olrn_time_sleep(int64_t ns) {\n"
    "    std::this_thread::sleep_for(std::chrono::nanoseconds(ns)); }\n"
    "\n"
    "/* std.math */\n"
    "static inline double _olrn_sqrt(double x)          { return std::sqrt(x); }\n"
    "static inline double _olrn_fabs(double x)          { return std::fabs(x); }\n"
    "static inline double _olrn_sin(double x)           { return std::sin(x); }\n"
    "static inline double _olrn_cos(double x)           { return std::cos(x); }\n"
    "static inline double _olrn_tan(double x)           { return std::tan(x); }\n"
    "static inline double _olrn_asin(double x)          { return std::asin(x); }\n"
    "static inline double _olrn_acos(double x)          { return std::acos(x); }\n"
    "static inline double _olrn_atan(double x)          { return std::atan(x); }\n"
    "static inline double _olrn_atan2(double y, double x){ return std::atan2(y,x); }\n"
    "static inline double _olrn_floor(double x)         { return std::floor(x); }\n"
    "static inline double _olrn_ceil(double x)          { return std::ceil(x); }\n"
    "static inline double _olrn_round(double x)         { return std::round(x); }\n"
    "static inline double _olrn_pow(double b, double e) { return std::pow(b,e); }\n"
    "static inline double _olrn_log(double x)           { return std::log(x); }\n"
    "static inline double _olrn_log2(double x)          { return std::log2(x); }\n"
    "static inline double _olrn_exp(double x)           { return std::exp(x); }\n"
    "\n"
    "/* std.str */\n"
    "static inline int64_t _olrn_str_len(const std::string& s) { return (int64_t)s.size(); }\n"
    "static inline int64_t _olrn_str_parse_int(const std::string& s) { return std::stoll(s); }\n"
    "static inline double  _olrn_str_parse_f64(const std::string& s) { return std::stod(s); }\n"
    "static inline std::string _olrn_str_upper(std::string s) {\n"
    "    std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return (char)std::toupper(c);});\n"
    "    return s; }\n"
    "static inline std::string _olrn_str_lower(std::string s) {\n"
    "    std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return (char)std::tolower(c);});\n"
    "    return s; }\n"
    "static inline std::string _olrn_str_trim(std::string s) {\n"
    "    s.erase(s.begin(), std::find_if(s.begin(),s.end(),[](unsigned char c){return !std::isspace(c);}));\n"
    "    s.erase(std::find_if(s.rbegin(),s.rend(),[](unsigned char c){return !std::isspace(c);}).base(), s.end());\n"
    "    return s; }\n"
    "static inline bool _olrn_str_starts(const std::string& s, const std::string& p) {\n"
    "    return s.rfind(p,0)==0; }\n"
    "static inline bool _olrn_str_ends(const std::string& s, const std::string& p) {\n"
    "    return s.size()>=p.size() && s.compare(s.size()-p.size(),p.size(),p)==0; }\n"
    "static inline bool _olrn_str_contains(const std::string& s, const std::string& p) {\n"
    "    return s.find(p)!=std::string::npos; }\n"
    "\n"
    "/* std.io */\n"
    "static inline int64_t _olrn_io_open(const std::string& path, int32_t mode) {\n"
    "    const char* modes[] = {\"r\", \"w\", \"r+\", \"a\"};\n"
    "    if (mode < 0 || mode > 3) return 0;\n"
    "    FILE* f = std::fopen(path.c_str(), modes[mode]);\n"
    "    return (int64_t)(uintptr_t)f; }\n"
    "static inline void _olrn_io_close(int64_t h) {\n"
    "    if (h) std::fclose((FILE*)(uintptr_t)h); }\n"
    "static inline std::vector<uint8_t> _olrn_io_read(int64_t h, int64_t n) {\n"
    "    std::vector<uint8_t> buf((size_t)n);\n"
    "    size_t r = std::fread(buf.data(), 1, (size_t)n, (FILE*)(uintptr_t)h);\n"
    "    buf.resize(r); return buf; }\n"
    "static inline void _olrn_io_write(int64_t h, const std::vector<uint8_t>& data) {\n"
    "    std::fwrite(data.data(), 1, data.size(), (FILE*)(uintptr_t)h); }\n"
    "static inline void _olrn_io_seek(int64_t h, int64_t pos, int32_t from) {\n"
    "    int whence[] = {SEEK_SET, SEEK_CUR, SEEK_END};\n"
    "    std::fseek((FILE*)(uintptr_t)h, (long)pos,\n"
    "               whence[(from >= 0 && from <= 2) ? from : 0]); }\n"
    "static inline int64_t _olrn_io_tell(int64_t h) {\n"
    "    return (int64_t)std::ftell((FILE*)(uintptr_t)h); }\n"
    "static inline std::string _olrn_io_readline(int64_t h) {\n"
    "    FILE* f = (FILE*)(uintptr_t)h;\n"
    "    std::string line; int c;\n"
    "    while ((c = std::fgetc(f)) != EOF && c != '\\n') line += (char)c;\n"
    "    return line; }\n"
    "static inline bool _olrn_io_eof(int64_t h) {\n"
    "    return std::feof((FILE*)(uintptr_t)h) != 0; }\n"
    "\n"
    "/* std.fs */\n"
    "static inline bool _olrn_fs_exists(const std::string& p) {\n"
    "    std::error_code ec; return std::filesystem::exists(p, ec); }\n"
    "static inline bool _olrn_fs_is_dir(const std::string& p) {\n"
    "    std::error_code ec; return std::filesystem::is_directory(p, ec); }\n"
    "static inline bool _olrn_fs_is_file(const std::string& p) {\n"
    "    std::error_code ec; return std::filesystem::is_regular_file(p, ec); }\n"
    "static inline bool _olrn_fs_mkdir(const std::string& p) {\n"
    "    std::error_code ec; return std::filesystem::create_directories(p, ec); }\n"
    "static inline bool _olrn_fs_rm(const std::string& p) {\n"
    "    std::error_code ec; return std::filesystem::remove(p, ec); }\n"
    "static inline int64_t _olrn_fs_rm_all(const std::string& p) {\n"
    "    std::error_code ec;\n"
    "    return (int64_t)std::filesystem::remove_all(p, ec); }\n"
    "static inline std::vector<std::string> _olrn_fs_ls(const std::string& p) {\n"
    "    std::vector<std::string> out; std::error_code ec;\n"
    "    for (auto& e : std::filesystem::directory_iterator(p, ec))\n"
    "        out.push_back(e.path().filename().string());\n"
    "    std::sort(out.begin(), out.end()); return out; }\n"
    "static inline int64_t _olrn_fs_size(const std::string& p) {\n"
    "    std::error_code ec;\n"
    "    auto n = std::filesystem::file_size(p, ec);\n"
    "    return ec ? -1 : (int64_t)n; }\n"
    "static inline bool _olrn_fs_rename(const std::string& a, const std::string& b) {\n"
    "    std::error_code ec; std::filesystem::rename(a, b, ec); return !ec; }\n"
    "static inline bool _olrn_fs_copy(const std::string& a, const std::string& b) {\n"
    "    std::error_code ec;\n"
    "    std::filesystem::copy(a, b,\n"
    "        std::filesystem::copy_options::overwrite_existing |\n"
    "        std::filesystem::copy_options::recursive, ec);\n"
    "    return !ec; }\n"
    "static inline std::string _olrn_fs_cwd() {\n"
    "    std::error_code ec;\n"
    "    return std::filesystem::current_path(ec).string(); }\n"
    "\n"
    "/* std.thread */\n"
    "template<typename Fn>\n"
    "static inline int64_t _olrn_thread_spawn(Fn fn) {\n"
    "    auto* t = new std::thread(fn);\n"
    "    return (int64_t)(uintptr_t)t; }\n"
    "template<typename Fn>\n"
    "static inline int64_t _olrn_thread_spawn_arg(Fn fn, int64_t arg) {\n"
    "    auto* t = new std::thread(fn, arg);\n"
    "    return (int64_t)(uintptr_t)t; }\n"
    "static inline void _olrn_thread_join(int64_t h) {\n"
    "    auto* t = (std::thread*)(uintptr_t)h;\n"
    "    if (t && t->joinable()) t->join();\n"
    "    delete t; }\n"
    "static inline void _olrn_thread_detach(int64_t h) {\n"
    "    auto* t = (std::thread*)(uintptr_t)h;\n"
    "    if (t && t->joinable()) t->detach();\n"
    "    delete t; }\n"
    "static inline void _olrn_thread_yield() { std::this_thread::yield(); }\n"
    "static inline int64_t _olrn_thread_id() {\n"
    "    return (int64_t)std::hash<std::thread::id>{}(std::this_thread::get_id()); }\n"
    "static inline int32_t _olrn_thread_cores() {\n"
    "    return (int32_t)std::thread::hardware_concurrency(); }\n"
    "/* std.thread mutex */\n"
    "static inline int64_t _olrn_mutex_new() {\n"
    "    return (int64_t)(uintptr_t)(new std::mutex()); }\n"
    "static inline void _olrn_mutex_lock(int64_t h) {\n"
    "    ((std::mutex*)(uintptr_t)h)->lock(); }\n"
    "static inline void _olrn_mutex_unlock(int64_t h) {\n"
    "    ((std::mutex*)(uintptr_t)h)->unlock(); }\n"
    "static inline void _olrn_mutex_free(int64_t h) {\n"
    "    delete (std::mutex*)(uintptr_t)h; }\n"
    "/* std.thread atomic i32 */\n"
    "static inline int64_t _olrn_atomic_new(int32_t v) {\n"
    "    return (int64_t)(uintptr_t)(new std::atomic<int32_t>(v)); }\n"
    "static inline int32_t _olrn_atomic_load(int64_t h) {\n"
    "    return ((std::atomic<int32_t>*)(uintptr_t)h)->load(); }\n"
    "static inline void _olrn_atomic_store(int64_t h, int32_t v) {\n"
    "    ((std::atomic<int32_t>*)(uintptr_t)h)->store(v); }\n"
    "static inline int32_t _olrn_atomic_add(int64_t h, int32_t v) {\n"
    "    return ((std::atomic<int32_t>*)(uintptr_t)h)->fetch_add(v); }\n"
    "static inline bool _olrn_atomic_cas(int64_t h, int32_t expected, int32_t desired) {\n"
    "    return ((std::atomic<int32_t>*)(uintptr_t)h)->compare_exchange_strong(expected, desired); }\n"
    "static inline void _olrn_atomic_free(int64_t h) {\n"
    "    delete (std::atomic<int32_t>*)(uintptr_t)h; }\n"
    "/* ── end olrn stdlib ─────────────────────────────────────────────── */\n";

#endif /* OLRN_STDLIB_IMPL_H */
