#ifndef OLRN_STDLIB_IMPL_H
#define OLRN_STDLIB_IMPL_H

/* C++ implementations injected when @libs.std is imported.
   All helpers use _olrn_ prefix to avoid collisions. */

static const char *STDLIB_IMPL =
    "/* ── olrn stdlib ───────────────────────────────────────────────── */\n"
    "#include <chrono>\n"
    "#include <thread>\n"
    "#include <cmath>\n"
    "#include <algorithm>\n"
    "#include <cctype>\n"
    "\n"
    "/* std.time */\n"
    "static inline int64_t _olrn_time_now() {\n"
    "    return std::chrono::duration_cast<std::chrono::nanoseconds>(\n"
    "        std::chrono::system_clock::now().time_since_epoch()).count(); }\n"
    "static inline int64_t _olrn_time_mono() {\n"
    "    return std::chrono::duration_cast<std::chrono::nanoseconds>(\n"
    "        std::chrono::steady_clock::now().time_since_epoch()).count(); }\n"
    "static inline void _olrn_time_sleep(int64_t ns) {\n"
    "    std::this_thread::sleep_for(std::chrono::nanoseconds(ns)); }\n"
    "\n"
    "/* std.math */\n"
    "static inline double _olrn_sqrt(double x)          { return std::sqrt(x); }\n"
    "static inline double _olrn_fabs(double x)          { return std::fabs(x); }\n"
    "static inline double _olrn_sin(double x)           { return std::sin(x); }\n"
    "static inline double _olrn_cos(double x)           { return std::cos(x); }\n"
    "static inline double _olrn_tan(double x)           { return std::tan(x); }\n"
    "static inline double _olrn_asin(double x)          { return std::asin(x); }\n"
    "static inline double _olrn_acos(double x)          { return std::acos(x); }\n"
    "static inline double _olrn_atan(double x)          { return std::atan(x); }\n"
    "static inline double _olrn_atan2(double y, double x){ return std::atan2(y,x); }\n"
    "static inline double _olrn_floor(double x)         { return std::floor(x); }\n"
    "static inline double _olrn_ceil(double x)          { return std::ceil(x); }\n"
    "static inline double _olrn_round(double x)         { return std::round(x); }\n"
    "static inline double _olrn_pow(double b, double e) { return std::pow(b,e); }\n"
    "static inline double _olrn_log(double x)           { return std::log(x); }\n"
    "static inline double _olrn_log2(double x)          { return std::log2(x); }\n"
    "static inline double _olrn_exp(double x)           { return std::exp(x); }\n"
    "\n"
    "/* std.str */\n"
    "static inline int64_t _olrn_str_len(const std::string& s) { return (int64_t)s.size(); }\n"
    "static inline int64_t _olrn_str_parse_int(const std::string& s) { return std::stoll(s); }\n"
    "static inline double  _olrn_str_parse_f64(const std::string& s) { return std::stod(s); }\n"
    "static inline std::string _olrn_str_upper(std::string s) {\n"
    "    std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return std::toupper(c);});\n"
    "    return s; }\n"
    "static inline std::string _olrn_str_lower(std::string s) {\n"
    "    std::transform(s.begin(),s.end(),s.begin(),[](unsigned char c){return std::tolower(c);});\n"
    "    return s; }\n"
    "static inline std::string _olrn_str_trim(std::string s) {\n"
    "    s.erase(s.begin(), std::find_if(s.begin(),s.end(),[](unsigned char c){return !std::isspace(c);}));\n"
    "    s.erase(std::find_if(s.rbegin(),s.rend(),[](unsigned char c){return !std::isspace(c);}).base(), s.end());\n"
    "    return s; }\n"
    "static inline bool _olrn_str_starts(const std::string& s, const std::string& p) {\n"
    "    return s.rfind(p,0)==0; }\n"
    "static inline bool _olrn_str_ends(const std::string& s, const std::string& p) {\n"
    "    return s.size()>=p.size() && s.compare(s.size()-p.size(),p.size(),p)==0; }\n"
    "static inline bool _olrn_str_contains(const std::string& s, const std::string& p) {\n"
    "    return s.find(p)!=std::string::npos; }\n"
    "/* ── end olrn stdlib ─────────────────────────────────────────────── */\n";

#endif /* OLRN_STDLIB_IMPL_H */
