[book]
title       = "The Oleren Programming Language"
authors     = ["cjRem44x"]
language    = "en"
src         = "src"

[build]
build-dir   = "../book_out"

[output.html]
site-url            = "/Oleren/"
git-repository-url  = "https://github.com/cjRem44x/Oleren"
edit-url-template   = "https://github.com/cjRem44x/Oleren/edit/main/book/src/{path}"
no-section-label    = false
additional-css      = ["theme/css/general.css"]
default-theme       = "coal"

[output.html.fold]
enable    = true
level     = 1
